logLevel: info
gnss:
  enable: true
  sendAsExternalGNSSSource:
    sendAsNMEA: true
    sendAsCoT: true
# Beyond Line of Sight (BLOS) communication settings
# This is only available for use on Mesh Gateways and
# hardware that supports it.
blos:
  enable: false
# Voice Comms
# This is only available on hardware that supports it.
comms:
  enable: false
  debug: false
  # The control source for the Push-to-Talk (PTT) functionality. Options include:
  # - openvlm: Use a Open Voice Link Module USB audio device for PTT control.
  # - nanoPTT: Use a NanoPTT device for PTT control.
  # - web: Use a web-based interface for PTT control.
  controlSource: openvlm

