logLevel: info
meshNetInterface: br-ahwlan
dbFile: /etc/openmanetd/openmanetd.db
gnss:
  enable: true
  sendAsExternalGNSSSource:
    sendAsNMEA: true
    sendAsCoT: true
alfred:
  mode: primary
  batInterface: bat0
  socketPath: /var/run/alfred.sock
  dataTypes:
    gateway: true
    node: true
    position: true
    addressReservation: true
comms:
  enable: false
  protocol: rtp
  debug: false
  controlSource: cm108
  nanoPTT:
    enable: false
    devicePath: /dev/hidraw0/*
    deviceName: Generic AB13X USB Audio
  bluetoothPtt:
    enable: false
    BluetoothAudioDeviceHint: ""
    BluetoothInputDevice: ""
    BluetoothOutputDevice: ""
